### ISSUE TITLE
Search causes 500 server error when search phrase contains one " character

### ISSUE THREAD

**Issue by laurisaarni** [Flowpack/Flowpack.SimpleSearch#19]
When using Flowpack.SimpleSearch.ContentRepositoryAdaptor the search crashes if the search phrase contains one " character.

Some examples of search phrases causing the error:

- "test
- test"

SQLite match statement gets malformed, most likely because SQLite uses " character in a similar way as MySQL uses ` to identify field name.

**Comment by iseries** [comment]
Could be fixed by change line 216 in sqLiteIndex.php:
`$statement->bindValue($parameterName, str_replace('"','',$parameterValue));`

**Comment by ndm2** [comment]
In `MATCH` expressions, double quotes act as phrase query delimiters, and they must come in pairs. If things haven't changed, then it isn't possible to query for tokens that contain `"`, however AFAIK matching will gracefully "ignore" them when they're wrapping a token, ie if the content for example contains the phrase

    "search" word

then matching on `search word` without the quotes would match just fine.

**https://www.sqlite.org/fts3.html#phrase**
**http://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg70848.html**

Just removing the quotes would remove that specific search feature, but I guess any solution to this would have its pros and cons. In case the phrase query functionality should be retained, then one solution would be to remove quotes only in case there's an uneven number of them, and that should probably be done on `SqLiteQueryBuilder` level, so that other types of searches/queries aren't being affected.

I could put a patch together, but I've just started looking into Neos this weekend, so I pretty much have zero experience with it yet, and I wouldn't be able to come up with proper tests for the time being. Also I'm not sure if this repo is still being maintained anyways? ping @kitsunet

**Comment by kitsunet** [comment]
Wow, this is old... I  kind of would say it's up to the implementation to escape/fix the serach query to work. It's the same in elasticserach, I can definitely produce broken search string if I just take user input and give it to elasticsearch, so same there, needs to be handled on the input side of things IMHO, because that's the only place you can decide what features you might want to allows.
